### ISSUE TITLE
Unable to make it work properly

### ISSUE THREAD

**Issue by maxdevjs** [sqozz/workspace.py#1]
Hello, I am quite new to yabar, but this was the missing feature in my opinion. Thank you for implementing it.

Anyway, when I start yabar the workspace block is **not** displayed. If I click randomly on other blocks (alternating?) the mouse buttons, I then get the following output:

![screenshot-2017-04-08_15 35 17_brt-03 00_1491676517](https://cloud.githubusercontent.com/assets/22229196/24831557/4908ffdc-1c72-11e7-8768-9667944d13da.png)

After the output is displayed:

- the whole bar becomes unresponsive (to clicks). Tested and confirmed.
- yabar crashed once. I do not know if it is related, I currently try to find it out.

```
Ubuntu 16.04 x86_64

i3 version 4.12-225-g7e00245 (2016-11-07, branch "gaps-next")

yabar v0.4.0-127-g96714d0

Python 3.5.2

```

I do not know what to look for. Any clue?

**Comment by sqozz** [comment]
Hi! I've added an example block to the [README.md](https://github.com/sqozz/workspace.py/blob/master/README.md). Looking at your screenshot tells me at least that "pango-markup: true" is missing in your config.
Can you try it out and report back if you got it working?

**Comment by maxdevjs** [comment]
Thank you for the reply. The example has really helped. I previously borrowed the configuration from this [ya_ws2](https://github.com/geommer/yabar/issues/144#issuecomment-289201510) and I did find out that:

- "pango-markup: true" was actually commented out
- type: "periodic" prevented the block to be displayed correctly (I guess)

Now everything seems to work fine (including urgent workspaces, not showed in the image) 

![screenshot-2017-04-08_23 30 27_brt-03 00_1491705027](https://cloud.githubusercontent.com/assets/22229196/24834147/7c5d25f2-1cb3-11e7-82ce-87e36b89e0d9.png)

Curiosity: could be possible to make every single workspace clickable (i.e. to switch to a workspace)?

**Comment by sqozz** [comment]
Nice to see it working now :)
No, clicking on single symbols is not possible with yabar. The only thing possible would be to write a script which gets fired when you right/left click on the whole module to switch to the left/right workspace. For me that was the reason to switch to polybar quiet quick.

**Comment by max-devjs** [comment]
Sorry for reopening this issue, just to report it: after a few seconds that I did send the comment, the workspaces blocks disappeared.

Anyway, polybar looks nice. Witch which wm are you using it?
